[build]
builder = "dockerfile"
dockerfilePath = "docker/Dockerfile.prod"
# Build arguments - Railway will use environment variables with the same name
buildArgs = ["NEXT_PUBLIC_BASE_URL"]

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
